[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.flash_mode = dio
lib_deps =
    paulstoffregen/OneWire
    milesburton/DallasTemperature

build_flags =
    -D CONFIG_FREERTOS_HZ=1000
    -D CONFIG_FREERTOS_USE_TICKLESS_IDLE_NONE
    -D CONFIG_FREERTOS_GENERATE_RUN_TIME_STATS=1
    -D CONFIG_FREERTOS_USE_TRACE_FACILITY=1
    -D CONFIG_FREERTOS_USE_STATIC_ALLOCATORS=1
